export const Selectors = {
	  navbar: '.main-menu',
    search: '.custom-search-input',
    wishlist: '.wishlist',
    filterColumn: '#filter_col',
    filterButton: '#ti-filter',
    listView: '.ti-view-grid',
    gridView: '.ti-view-list',
    addToFavorites: '.grid_item> ul > li:nth-child(1)',
    addToCompare: '.grid_item> ul > li:nth-child(2)',
    addToCart: '.grid_item> ul > li:nth-child(3)',
    quickLinks: '#collapse_1 > ul',
    contacts: '#collapse_3 > ul',
    keepInTouch: '#email_newsletter',
    colorBlack: '#colors__Black',
    filterConfirm: '#filterBtn',
    filterReset: '#resetBtn',
    productGrid: '#product_grid',
    productItem: '.bg_gray',
    shoeName: '#shoe_name',
    newPrice: '#new_price',
    oldPrice: '#old_price',
    size: '.custom-select-form .current',
    code: '.prod_info > p > small'
  };